[package]
name = "dobf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
lazy_static = "1.4.0"
log = "0.4.20"
simple_logger = "4.3.0"
toml = "0.8.8"

[profile.release]
panic = "abort"
strip = true
lto = true
codegen-units = 1
debug = false
